# Generated by Django 5.1.5 on 2025-02-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('seller', 'Seller')], default='farmer', max_length=10),
        ),
    ]
