# Generated by Django 5.1.6 on 2025-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('fertilizer_type', models.CharField(blank=True, max_length=200, null=True)),
                ('application_date', models.DateField()),
                ('sms_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
